In [66]:
import pandas as pd
#city_pop = pd.read_csv("sub-est2021_all.csv",encoding='latin-1')
#city_land = pd.read_csv("2020_Gaz_place_national.txt",sep = "\t",encoding='latin-1')
#age_sex = pd.read_csv("Age_and_Sex_2021-Data.csv",encoding='latin-1')
#education = pd.read_csv("Education_2021-Data.csv",encoding='latin-1')
#housing = pd.read_csv("Housing_2021-Data.csv",encoding='latin-1')
#race = pd.read_csv("Race_2020.p1-Data.csv",encoding='latin-1')

#state_codes = pd.read_csv("state_codes.csv")

In [88]:
city_pop = pd.read_csv("sub-est2021_all.csv",encoding='latin-1')
state_codes = pd.read_csv("state_codes.csv")

city_pop = city_pop[["NAME", "STNAME","POPESTIMATE2021"]]
remove_states = [not i for i in city_pop["NAME"] == city_pop["STNAME"]]
remove_county = [not i.lower().__contains__("county") for i in city_pop["NAME"]] 
city_pop = city_pop[remove_states and remove_county]
city_pop = city_pop[city_pop["POPESTIMATE2021"]>=50000]
city_pop = city_pop.set_axis(['city', 'state', 'pop_estimate_2021'], axis='columns', copy = False)
state_codes = state_codes[["state","code"]].set_axis(['state', 'state_code'], axis='columns', copy = False)
city_pop = pd.merge(city_pop,state_codes, on = "state", how = "left")
city_pop["city_state"] = city_pop["city"] + ", " + city_pop["state"]
city_pop

,city,state,pop_estimate_2021,state_code,city_state
0,Alabama,Alabama,5039877,AL,"Alabama, Alabama"
1,Auburn city,Alabama,78564,AL,"Auburn city, Alabama"
2,Birmingham city,Alabama,197575,AL,"Birmingham city, Alabama"
3,Decatur city,Alabama,57804,AL,"Decatur city, Alabama"
4,Dothan city,Alabama,71175,AL,"Dothan city, Alabama"
...,...,...,...,...,...
2235,Wyoming,Wyoming,578803,WY,"Wyoming, Wyoming"
2236,Casper city,Wyoming,58656,WY,"Casper city, Wyoming"
2237,Cheyenne city,Wyoming,65051,WY,"Cheyenne city, Wyoming"
2238,Cheyenne city,Wyoming,65051,WY,"Cheyenne city, Wyoming"
2239,Casper city,Wyoming,58656,WY,"Casper city, Wyoming"

In [87]:
city_land = pd.read_csv("2020_Gaz_place_national.txt",sep = "\t",encoding='latin-1')
state_codes = pd.read_csv("state_codes.csv")

test = city_land[["USPS","NAME","ALAND"]].set_axis(['state_code', 'city', 'land_area'], axis='columns', copy = False)
city_land = pd.merge(test,state_codes[["state","code"]], left_on = "state_code", right_on = "code", how = "left")
city_land = city_land.dropna()
del city_land["code"]
city_land["city_state"] = city_land["city"] + ", " + city_land["state"]
city_land

,state_code,city,land_area,state,city_state
0,AL,Abanda CDP,7764034,Alabama,"Abanda CDP, Alabama"
1,AL,Abbeville city,40255362,Alabama,"Abbeville city, Alabama"
2,AL,Adamsville city,67895675,Alabama,"Adamsville city, Alabama"
3,AL,Addison town,9753293,Alabama,"Addison town, Alabama"
4,AL,Akron town,1776165,Alabama,"Akron town, Alabama"
...,...,...,...,...,...
31612,WY,Woods Landing-Jelm CDP,43264734,Wyoming,"Woods Landing-Jelm CDP, Wyoming"
31613,WY,Worland city,11882743,Wyoming,"Worland city, Wyoming"
31614,WY,Wright town,7872147,Wyoming,"Wright town, Wyoming"
31615,WY,Yoder town,550880,Wyoming,"Yoder town, Wyoming"
31616,WY,Y-O Ranch CDP,6220116,Wyoming,"Y-O Ranch CDP, Wyoming"

In [117]:
walking_data = pd.merge(city_pop,city_land, on = "city_state", how = "inner")
walking_data.set_axis([i.replace("_x","") for i in list(walking_data)], axis='columns', copy = False)
[i.__contains__("_y") for i in list(walking_data)]

[False, False, False, False, False, True, True, False, True]